[package]
name = "artefacta"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
edition = "2018"

[dependencies]
petgraph = "0.5.0"
anyhow = "1.0.26"
bidiff = "0.1.0"
bipatch = "0.1.0"
zstd = "0.5.1"

[dev-dependencies]
tempfile = "3.1.0"
rand = "0.7.3"
