[package]
name = "artefacta"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
log = "0.4.8"

petgraph = "0.5.0"

bidiff = "0.1.0"
bipatch = "0.1.0"
zstd = "0.5.1"

structopt = "0.3.11"
color-backtrace = "0.3.0"
pretty_env_logger = "0.4.0"

url = "2.1.1"
tar = "0.4.26"
walkdir = "2.3.1"
# rusoto_s3 = { version = "0.43.0-beta.1", features = ["rustls"], default-features = false }

[dev-dependencies]
tempfile = "3.1.0"
rand = "0.7.3"
proptest = "0.9.5"
