[package]
name = "erreur"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
eyre = "0.6"
color-eyre = { version = "0.5", default-features = false }
