[package]
name = "erreur"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
color-eyre = { version = "0.5", default-features = false }
log = "0.4.8"
